spring.application.name=foodiesapi

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodies
spring.data.mongodb.database=foodies

# Cloudinary Configuration
cloudinary.cloud_name=dxglmwlqa
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# JWT Configuration
jwt.secret.key=${JWT_SECRET}

# Razorpay Configuration
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}

# File Upload Directory
file.upload-dir=uploads

# Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY}