spring.application.name=foodiesapi

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodies
spring.data.mongodb.database=foodies

# Cloudinary Configuration
cloudinary.cloud_name=test
cloudinary.api_key=test
cloudinary.api_secret=test

# JWT Configuration
jwt.secret.key=mysecretkey123456789123456789123456

# Razorpay Configuration
razorpay_key=test
razorpay_secret=test

# File Upload Directory
file.upload-dir=uploads

# Gemini AI Configuration
gemini.api.key=test